### ISSUE TITLE
Updating tokens state  does not update field

### ISSUE THREAD

**Issue by hughc** [shahar-levi/react-tokenfield#5]
I have a form with a TokenField that I wish to reuse / redraw based on different selected items in my app. Changes in the selected item update the component state that supplies the tokens property, but the tokenfield does not re-render

Simple working example: 
https://codesandbox.io/embed/react-functional-component-forked-m27vlw?fontsize=14&hidenavigation=1&theme=dark

When you click the two refresh buttons,  the text summary updates correctly with `one, two, three` or `aay, bee, cee`, so that state is updated correctly, but the tokens in the field retain the initial value of `dog`  `cat`  `fish`. It is as though the token property is only read on initial render, and subsequent re-renders do not occur if that property is updated from an external source (only from internal events).

I'm a React novice, so happy to hear if I'm approaching it the wrong way.

**Comment by shahar-levi** [comment]
Hi @hughc ,
Sorry i missed your message.
Is it still relevant?

**Comment by hughc** [comment]
Yes, I haven't found a solution to the issue. Please review the codesandbox link.

**Comment by hughc** [comment]
Thanks for the fix.
