### ISSUE TITLE
Options component goes beyond the container

### ISSUE THREAD

**Issue by Vittor-Emanoel** [shahar-levi/react-tokenfield#6]
Hi, I'm having a problem with the options dropdown. They go beyond the width and don't fit, how could I fix them? Is there anything I could do to make the dropdown adjusted?

I look forward to hearing from you, thank you!

![Captura de tela 2024-06-25 143916](https://github.com/shahar-levi/react-tokenfield/assets/55211291/751a8795-cef1-498c-b7fd-8552b77d43a5)

**Comment by shahar-levi** [comment]
Thanks for using this component.
Fixed 🥳
