### ISSUE TITLE
I can't run the application locally

### ISSUE THREAD

**Issue by Vittor-Emanoel** [shahar-levi/react-tokenfield#7]
![image](https://github.com/shahar-levi/react-tokenfield/assets/55211291/c8830b96-4ea1-49f2-bda7-99b6b306c99f)
Hello!

How do I test react-tokenfield locally?

I try, but I can only run the example.

**Comment by shahar-levi** [comment]
```npm i``` 
```npm build```
the navigate to example folder and run
 ```npm i``` 
 ```npm start```
